### ISSUE TITLE
Error while creating a clan

### ISSUE THREAD

**Issue by fhxserver** [UltraPowaDev/UCS#1]
Hello appropriate title, I want to know, if ucs now experiencing a bug after making clan.

clay screenshot : http://i.imgur.com/FUtOloO.jpg (http://prntscr.com/as08b9)

you try to create a clan, keep restarting the emulator, and open coc you, it would have experienced the same problem with my screenshot.

Please developers checked.

**Comment by DaividSmith** [comment]
after new update by aidid again new Bug accurded...
when you make a clan or Join a clan you see clan tab empty...
http://imgur.com/8Wh4k0w

**Comment by aididhaiqal** [comment]
Yep,I notice that issue but at least its fix some bug....New commit will come anyway

**Comment by aididhaiqal** [comment]
[UCS][14301] Processing CreateAllianceMessage (33, Aidid)
[UCS][24111] Processing AvailableServerCommandMessage (33, Aidid)
[UCS][14102] Processing ExecuteCommandsMessage (33, Aidid)
         The command '4265231321' has been ignored
[UCS][10108] Processing KeepAliveMessage (33, Aidid)
[UCS][20108] Processing KeepAliveOkMessage (33, Aidid)
[UCS][14102] Processing ExecuteCommandsMessage (33, Aidid)
         The command '2736523226' has been ignored
[UCS][10108] Processing KeepAliveMessage (33, Aidid)
[UCS][20108] Processing KeepAliveOkMessage (33, Aidid)
[UCS][14102] Processing ExecuteCommandsMessage (33, Aidid)
         The command '2334777025' has been ignored

Bug checked and its cause by COC client it self

**Comment by aididhaiqal** [comment]
Temp solution is, Reopen coc after create clan

**Comment by DaividSmith** [comment]
very Thanks aidi..you are very celever bro

**Comment by smartclash** [comment]
yeah @DaividSmith

**Comment by DaividSmith** [comment]
Again Leave Clan problem Back! you can not leave Clan and when you press on Leave Bottun when exit from clinet...if you Run clinet again Hang on Loading and not enter to game :(

**Comment by aididhaiqal** [comment]
@DaividSmith Never hapend to me bro.Maybe your ucs stop listening connetion?Try restart

**Comment by BerkanYildiz** [comment]
When you don't know how to use this emulator, just don't ..?
