### ISSUE TITLE
Clan Leave Issue

### ISSUE THREAD

**Issue by DaividSmith** [UltraPowaDev/UCS#12]
Hi
this issue 100% confirmed for a lot of users and devices,,,
1 - creat a clan
2 - for 2 min wait on clan till some one join to clan
3 - now click on leave bottun,,
you will see cant leave from clan and when you exit from clinet and start again loading fill 100% but cant enter to village :(
(i always empty Sql databse for my tests.so i am sure this is not for my database)

**How we can fix ?**
user should Clear data of Clinet for enter to clinet!

this problem was not on 10 days ago in ucs! i think some thing change in codes that accurd this problem...

**Comment by aididhaiqal** [comment]
Thanks for the report

**Comment by aididhaiqal** [comment]
Anyway,Please show us Error Message on console

**Comment by DaividSmith** [comment]
ok i will upload photos and error log soon...this issue is so seroius

**Comment by BerkanYildiz** [comment]
Fixed.
