### ISSUE TITLE
Database bugs

### ISSUE THREAD

**Issue by ClashofJeann** [UltraPowaDev/UCS#15]
Hi,
I have some issue with database (sqlite and ucsdb)
-Player forms 200 troops and has only 1 when attacking, after the player want to go home then it crashes. (unable to play without creating a new account)
Is it from my side ?
Thank you

**Comment by smartclash** [comment]
@ClashofJeann Ucs saving functionality not yet done. So even after training troops, it doesn't save to database and the user has only one to attack

###Temp. FIX

Train troops, wait for three minutes and then attack. For server with more people, have to wait more than three minutes.

Or you can execute the command /saveall in the global chat (should be admin) after training troops.

**Comment by ClashofJeann** [comment]
Ok thank you! 
I hope it will be fixed soon!

**Comment by smartclash** [comment]
@ClashofJeann Iit will be. Please close this issue if you want.
