### ISSUE TITLE
Clan Tab not shown after creat clan

### ISSUE THREAD

**Issue by DaividSmith** [UltraPowaDev/UCS#19]
hello
Creat clan and veiw a clan for JOIN. you can not see clan tab and you must exit from game and run again for see Clan tab

**Comment by aididhaiqal** [comment]
We know as we remove "Out Of Sync: after create clan

**Comment by DaividSmith** [comment]
i tjink thins version is Perfect!
please if you can fix this problem or for temp add out of sync after crat clan...
because i think only problem that i said

**Comment by aididhaiqal** [comment]
Problem is now recognize,The problem is,After clan creation, UCS fail to decrypt "Some" SecrectBox Packet.Fix comming real soon

**Comment by DaividSmith** [comment]
NEW Problem in lastest commit https://github.com/UltraPowaDev/UCS/commit/769a7f408f80f3f4dd4dc3724b1e0974505c3d58

after creat clan by any person , cant leave from clan...after click on leave clan botton ...all useres disconeting from server and no one can login to server and get login faild!!

sorry for my bad english!

**Comment by BerkanYildiz** [comment]
Bug found.

**Comment by DaividSmith** [comment]
very good bro...i hope fixing soon...thanks again for consideration @BerkanYildiz
