### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by smartclash** [UltraPowaDev/UCS#2]
After compiling, I am unable to connect and play.

It does show client connected but then throws login failed in the client side. I am using the patched APK. 

I know it is an issue with the code. Check it out, users are unable to login!

**Comment by aididhaiqal** [comment]
This happend when the last ucs commit called "User token" This commit effected clans feature which prevent the ucs to reply to users when anybody create a clan.Work is on progress

**Comment by smartclash** [comment]
@aididhaiqal But the problem is the person is not even able to login.

**Comment by ADeltaX** [comment]
It's a problem of the server because it doesn't store it.
@aididhaiqal fixed it.

**Comment by aididhaiqal** [comment]
Fixed i think
