### ISSUE TITLE
Troops - Not saving!

### ISSUE THREAD

**Issue by smartclash** [UltraPowaDev/UCS#20]
After training troops, when your go for an attack, you can not see the troops and it asks us again to train troops. But when training, the console shows the message : 

         Processing TrainUnitCommand
         Processing TrainUnitCommand
         Processing TrainUnitCommand
         Processing TrainUnitCommand
         Processing TrainUnitCommand
         Processing TrainUnitCommand
         Processing TrainUnitCommand
         Processing TrainUnitCommand
         Processing TrainUnitCommand
         Processing TrainUnitCommand
         Processing TrainUnitCommand

But still we can not attack. This is a major issue. 

Another issue is that the wifi signal keeps on shwoing even if we run the server locally (The 192.168.1.1 method) and says lost connection with the server during gameplay which is worst.

And more, after the commit 3348c83, all seem to be a bit slow. And the UCS takes a lot of memory for just 5 players (compared to the older commits)

Anyways, i think you should take these into consideration and make UCS better

**Comment by aididhaiqal** [comment]
Hi,Training Troop bug was known a few day ago.Our guys has detected major change in Characters.csv which make any troop train detected as "Non Troop" by ucs.We are working on fixinf this.Also we are Investigating issue with https://github.com/UltraPowaDev/UCS/commit/3348c83330a66da98ccdb14a16b2e2b0990d1e3f

**Comment by smartclash** [comment]
Yeah, thanks for a faster reply. May you please check this also?

![whatisthis_](https://cloud.githubusercontent.com/assets/16922883/14767128/4428658c-0a3c-11e6-9793-1e1bada86094.png)
@aididhaiqal

**Comment by aididhaiqal** [comment]
Hi,I will check it after i'm done creating an alpha ipa for UCS

**Comment by smartclash** [comment]
Thank you very much @aididhaiqal  Take your time

**Comment by aididhaiqal** [comment]
IOS Support Comming Soon!

**Comment by aididhaiqal** [comment]
![Commingsoon_](https://cloud.githubusercontent.com/assets/10329190/14767178/277dec8e-0a52-11e6-8bf3-030f7c2b345d.png)
IOS Support Comming Soon!

**Comment by smartclash** [comment]
aww man, that's unbelievable. Keep Going Aidid!

**Comment by aididhaiqal** [comment]
![image](https://cloud.githubusercontent.com/assets/10329190/14809415/7ab0ac70-0bbf-11e6-9a8c-86d8d817186f.png)
Bug consindered as fake
