### ISSUE TITLE
Sql Server

### ISSUE THREAD

**Issue by DominikMC** [UltraPowaDev/UCS#21]
`[UCS]    Packet Manager started successfully
[UCS]    Message manager has been successfully started !
[UCS]    An unknown exception occured when trying to connect to the sql server.
[UCS]    Please check your database configuration !`

I keep getting this on startup, I think its a bug not sure, please check it out, Thanks!

**Comment by aididhaiqal** [comment]
Its not a bug, Your database is down

**Comment by DominikMC** [comment]
Can you please tell me how to fix this (I didn't have a problem with this in the previous builds).

**Comment by DarkSoulCoC** [comment]
did you config the ucsconf file with correct details?

**Comment by DaividSmith** [comment]
[UCS] Packet Manager started successfully [UCS] Message manager has been successfully started ! [UCS] An unknown exception occured when trying to connect to the sql server. [UCS] Please check your database configuration !
i have this problem...and recheck all details and all is true!!!

**Comment by DarkSoulCoC** [comment]
and did you try clearing/re-importing database in ur server?

**Comment by DominikMC** [comment]
@DarkSoulCoC Yes it works for ucsdbEntities but doesn't save at all.
If I try sqliteEntites still same error.

**Comment by DominikMC** [comment]
@DaividSmith No it's not.

**Comment by DaividSmith** [comment]
@DarkSoulCoC
Yes...i think this is new issue...all changes in game not SAVED!!!

**Comment by DominikMC** [comment]
Closing this issue as it has been solved and made a new issue about the saving.
Thanks for the support!
