### ISSUE TITLE
Connections problems

### ISSUE THREAD

**Issue by ClashofJeann** [UltraPowaDev/UCS#22]
Hi,
I have a big issue with latest commit:
After starting when 2-10 connectes at the same time ucs crashes. error "too much request" something like that..
Any help to provide or needs a fix?
Thank you for your work.

**Comment by BerkanYildiz** [comment]
Hello,

Can you provide a screenshot of this error please ?

**Comment by ClashofJeann** [comment]
Of course
[http://imgur.com/o2iTi0N](url)

**Comment by BerkanYildiz** [comment]
This is not an UCS problem, just your servers status checker or whatever doing too many request, you can simply disable the api for the moment.
Explaination -> Something is "ddosing" your API.

**Comment by ClashofJeann** [comment]
oh but in config files no options to disable it (or tell me how)

**Comment by DarkSoulCoC** [comment]
just change you API port? or enable firewall

**Comment by aididhaiqal** [comment]
This bug is due to new IP Checker,Fix comming soon

**Comment by aididhaiqal** [comment]
Fixed in latest commit
