### ISSUE TITLE
No Saving

### ISSUE THREAD

**Issue by DominikMC** [UltraPowaDev/UCS#23]
UCS doesn't save anything at all!
I am not the only one who has this bug.

The "All data has bee saved" is missing from UCS.

Hope to hear from you soon.

PS: If it is just something from my side, please let me know how I can fix it, thanks!

**Comment by DaividSmith** [comment]
Its confirmed
this is because of some new changes and clean up by @BerkanYildiz
all files and codes changed and i think @BerkanYildiz fix this issue very sooon!

**Comment by aididhaiqal** [comment]
Problem issue found,UCS Save the user info but turn out,On every login there is a fail for check if the user is already in db,So ucs create a new entry for the player

**Comment by BerkanYildiz** [comment]
Checked, re-checked, and re-rechecked, everything is working fine for me.

**Comment by DominikMC** [comment]
@aididhaiqal Do you know how to fix it?

**Comment by DominikMC** [comment]
@BerkanYildiz But not for me

**Comment by DominikMC** [comment]
Fixed in latest commit, Thanks!

**Comment by DaividSmith** [comment]
yes
YOU SHOULD Clear DATA in Clinet,,,,and this problem fixed by this way
