### ISSUE TITLE
Login Database "NoNameYet"

### ISSUE THREAD

**Issue by DominikMC** [UltraPowaDev/UCS#25]
Bug:
UCS saves the player to the database.
Every time they exit and login it starts back with "NoNameYet" but the user is already on ucsdb.

**Comment by aididhaiqal** [comment]
Does it happend as new acc?

**Comment by DaividSmith** [comment]
@DominikMC

You Must Clear Data in clinet and this will fix by this work

**Comment by BerkanYildiz** [comment]
Wrong, as i already said.

**Comment by DominikMC** [comment]
@aididhaiqal yes in the newest commit

**Comment by DominikMC** [comment]
@davidsmith how?

**Comment by DominikMC** [comment]
@BerkanYildz Then please help me and tell me how to fix it.

**Comment by DaividSmith** [comment]
go to APPS or APPS manager
find Ultrapowa app
and click on clear data
like this photo :
![2016-04-26_8-01-02](https://cloud.githubusercontent.com/assets/18288107/14805859/252ee008-0b85-11e6-8b27-4f19843580bd.jpg)

**Comment by DominikMC** [comment]
Thanks, how about iOS?

**Comment by DominikMC** [comment]
Same thing happens there.
