### ISSUE TITLE
[Question]Ultrapowa Client Patcher

### ISSUE THREAD

**Issue by parnz** [UltraPowaDev/UCS#26]
I can use Ultrapowa Client Patcher on the **current CoC version on Play Store** to make it compatible to latest commit UCS source on this repo?
If not, Where I can find the compatible apk.

(The I tried an apk downloaded from wiki. It force close and ucs throw an error socket closed by remote host.)

Thanks.

**Comment by aididhaiqal** [comment]
This not an issue and yes you can,But better wait until wiki is done which is this week

**Comment by parnz** [comment]
Ok, After cleared apk's data in android settings it connected now.
