### ISSUE TITLE
Patching problem

### ISSUE THREAD

**Issue by ClashofJeann** [UltraPowaDev/UCS#28]
Hi,
I've updated to latest source my server but when players download patch files they crash (was working before very fine)
error:
20160426150058	[UCS]    The client '191.247.231.36' throw an exceptionSystem.Net.Sockets.SocketException (0x80004005): An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at UCS.Core.Network.SocketRead.OnReceive(IAsyncResult result)
System.Net.Sockets.SocketException (0x80004005): An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at UCS.Core.Network.SocketRead.OnReceive(IAsyncResult result)

**Comment by ClashofJeann** [comment]
anyone?

**Comment by BerkanYildiz** [comment]
Take the latest source

**Comment by ClashofJeann** [comment]
taken so now another issue so I close  the report and start a new issue

**Comment by ClashofJeann** [comment]
The same problem with the newest source

**Comment by BerkanYildiz** [comment]
Socket issue, not patching issue..

**Comment by Knightking10** [comment]
ok
