### ISSUE TITLE
Cliënt saving

### ISSUE THREAD

**Issue by palafix** [UltraPowaDev/UCS#29]
In have a problem when saving players. 
I have 3 mobile phones for testing and only 1 is saved. 
2 samsung devices and 1 iPhone 4. 
1 samsung is saved the other phones are saved to db but when I log out and then log in it greats a new account. 
I hope you can help. I compiled the newest on this time.

**Comment by BerkanYildiz** [comment]
Confirmed,i just tested and it happen.
I need to look at it.

**Comment by palafix** [comment]
Oke thnx for the quick response. 
I will wait for the fix

**Comment by DominikMC** [comment]
But when I allready reported that issue, it was "apparently" fixed.

**Comment by DaividSmith** [comment]
i think this bug Fixed after https://github.com/UltraPowaDev/UCS/commit/ea9f60f8cf701555ed241bc93f1557a2020df4bd  fixed

make sure clean databse first

**Comment by palafix** [comment]
Oké I will test it. 
I tel if it works for me.

**Comment by palafix** [comment]
not fixed yet

**Comment by palafix** [comment]
Hello, I have still the problem with account saving.
On Android it's oke but on ios it's not, is it a problem on my or is it something else.

**Comment by BerkanYildiz** [comment]
Fixed, you also need a good mysql server, not a "noob-made".
