### ISSUE TITLE
Server Hackable

### ISSUE THREAD

**Issue by smartclash** [UltraPowaDev/UCS#3]
I don't know how but some user is hacking the server and it displays `Hacked, Hacked, Hacked, Hacked ,Hacked` and goes offline. Please take a look at this security issue.

**Comment by aididhaiqal** [comment]
That username i think

**Comment by smartclash** [comment]
lol no, it just displays the phrase and ucs shuts down!

**Comment by BerkanYildiz** [comment]
Not possible.

**Comment by smartclash** [comment]
@BerkanYildiz Okay, i will send you guys a screenshot when i get it!

**Comment by DominikMC** [comment]
That is just someone typing in global chat

**Comment by DominikMC** [comment]
And in the previous version there was a big with global chat where UCS would crash.
