### ISSUE TITLE
Crash on UCS

### ISSUE THREAD

**Issue by DaividSmith** [UltraPowaDev/UCS#30]
hello to all developers

lastest ucs commits  https://github.com/UltraPowaDev/UCS/commit/62c889f39d1c28ea6b5892bcf6c07bf7e0a9875a

have serios crash problem...when you creat troops not saving and when you go to Attack you crashing and cant come back again to clinet
please view this Video that i record from my server and clinet

[crash.ucs.zip](https://github.com/UltraPowaDev/UCS/files/237924/crash.ucs.zip)

**Comment by aididhaiqal** [comment]
Closed as this confirm as client problem

**Comment by DaividSmith** [comment]
so this is Jus my problem?
i check this problem with a lot of apk and devices!! 
please give me a link of working apk for compatible with new ucs..tnx

**Comment by aididhaiqal** [comment]
Turn out,New UCS bug come after few berkan commit.Bug is not being recognize yet

**Comment by aididhaiqal** [comment]
Consider as fixed,Please re-open the issue again if im wrong

**Comment by DaividSmith** [comment]
yes broooooooo...This fixed 100%
