### ISSUE TITLE
crash when click on leag

### ISSUE THREAD

**Issue by DaividSmith** [UltraPowaDev/UCS#34]
hi to devolepers ..we miss you :(

i found new bug...
when user want click on leage window clinet crashing...

**Comment by aididhaiqal** [comment]
Ok will check

**Comment by BerkanYildiz** [comment]
**Clinet, Clinet, Clinet, Clinet, Clinet, Clinet, Clinet, Clinet, Clinet, Clinet, Clinet, Clinet, Clinet, Clinet, Clinet, Clinet, Clinet, Clinet, Clinet, Clinet, Clinet, Clinet, Clinet, Clinet, Clinet, Clinet, Clinet, Clinet, Clinet, Clinet, Clinet, Clinet, Clinet, Clinet, Clinet, Clinet, Clinet, Clinet, Clinet, Clinet, Clinet, Clinet, Clinet, Clinet, Clinet, Clinet, Clinet, Clinet, Clinet, Clinet, Clinet, Clinet, Clinet, Clinet, Clinet, Clinet, Clinet, Clinet, Clinet, Clinet, Clinet, Clinet, Clinet, Clinet, Clinet, Ahhhhhh**

**Comment by DaividSmith** [comment]
@BerkanYildiz
glad to see you broooooooooooooooooooooo....
i just change ip in your offical apk not more!!!!

**Comment by smartclash** [comment]
Please as said, describe your problem neat and clean! If you have any bugs and errors during gameplay, please describe with these information : 

* A copy of the log files (don't copy paste)
* Message in console during the error (screenshot)
* Error with client

And of course, please go to http://www.5minuteenglish.com/ to learn some english or use https://translate.google.com/ to translate things!

Warm regards,
Alpha Man

**Comment by BerkanYildiz** [comment]
No infos.
