### ISSUE TITLE
Recompile error

### ISSUE THREAD

**Issue by hnomkeng** [UltraPowaDev/UCS#36]
Original Apk
[Ultrapowa-Patched-8.212.9-5.0ready.apk_2016-05-14-_18-27.txt](https://github.com/UltraPowaDev/UCS/files/264493/Ultrapowa-Patched-8.212.9-5.0ready.apk_2016-05-14-_18-27.txt)

**Comment by Driesboy** [comment]
i cannot decompile it

**Comment by Driesboy** [comment]
i will compile it for you with android studio if you want

**Comment by hnomkeng** [comment]
complie with android studio only ?

**Comment by Driesboy** [comment]
yes

**Comment by Driesboy** [comment]
can you give me the zip file??

**Comment by hnomkeng** [comment]
OK, I will complie with android studio again.

Thank you sir.

**Comment by Driesboy** [comment]
Can you give me the coc sources please?
Op 15-mei-2016 07:53 schreef "Hnomkeng.Big" <notifications@github.com>:

**Comment by hnomkeng** [comment]
https://mega.nz/#!JY0BhCgI!D5ergSqoPKVpmJG6kV9B75XaF0p8cKVMf8CuI_Jk4mA

Thank you. @Driesboy

**Comment by Driesboy** [comment]
nono thank u

**Comment by Driesboy** [comment]
1 question my coc crash if i use this how can i fix that

**Comment by Driesboy** [comment]
@hnomkeng i need the sources not the apk

**Comment by hnomkeng** [comment]
sources in rar.

**Comment by Driesboy** [comment]
ok

**Comment by Driesboy** [comment]
my coc crash after join

**Comment by BerkanYildiz** [comment]
Just delete the lines 3 and 4 in "\res\values-v23\styles.xml"...
