### ISSUE TITLE
Fix !

### ISSUE THREAD

**Issue by TokyoSU** [UltraPowaDev/UCS#38]
With last update if i click safe cog i got this error:
20160529085311		 Processing MissionProgressCommand
20160529085311		 The command '21000012' has been ignored
please fix!
Update bugged to.

**Comment by smartclash** [comment]
As i see from my point of my view, this command is not yet over. We have not yet built it fully. Please do close this issue by your self

**Comment by TokyoSU** [comment]
And for Update COC bug ?

**Comment by smartclash** [comment]
it will be fixed in a month or so. In our private development, all the bugs are fixed (nearly)

**Comment by TokyoSU** [comment]
Ok thanks for info i close issue
