### ISSUE TITLE
UCS Will Not Support Latest CoC

### ISSUE THREAD

**Issue by aididhaiqal** [UltraPowaDev/UCS#39]
Hey,UCS Will Not Work With Latest COC....Supercell succeed....They change a lot thing and we defeated ~UCS Dev Team [img](http://telecoms.com/wp-content/blogs.dir/1/files/2013/01/white-flag-300x258.jpg)

**Comment by TokyoSU** [comment]
But GoblinLand have the last version ?
Just recode for work ?
You abandon so quickly ?
You only relied on only barkan ?
you-have a community behind you and you, you want all disappointed ?
If you have "courage", keep going!

**Comment by aididhaiqal** [comment]
TokyoSU,I think i should be OK to leave a community behind.Because the "Comunnity Leader" leave us behind...Thats why we wont work on UCS.Also GCS got it work because GCS using newest crypto system meanwhile UCS using old one that we created before

**Comment by TurdinatorOG** [comment]
Is there anyway to fix the Crypto system? i know a little C# and i'm learning quickly but i know nothing about Crypto ananlytics, is there anyway to fix UCS and how much work is it going to take to get it as stable as the actual servers.

**Comment by TurdinatorOG** [comment]
please i genuinly feel that UCS is something special if you leave it where it is you let it die along all of your hard work and community support.

**Comment by aididhaiqal** [comment]
We have been loyal to UCS before but Eiffel turn's other way.

**Comment by TurdinatorOG** [comment]
that doesn't mean you have to, do code on the application or what do u do ?

**Comment by TurdinatorOG** [comment]
do you code, how much work is required to get it where it needs to be?

**Comment by TokyoSU** [comment]
But fix patch problem and after leave :dash:

**Comment by ClashofJeann** [comment]
+1

**Comment by aididhaiqal** [comment]
LOL

**Comment by TurdinatorOG** [comment]
aididhaiqal, if your going to leave can i at least have your latest work, so i can pick up where you guys left off. if you wannt to leave that's fine, we can have a new DEV team.

**Comment by BerkanYildiz** [comment]
LOL

**Comment by BerkanYildiz** [comment]
We are not robots. 
If you want a working UCS, then work on it, we don't really care, we are not under your "orders".
